name: Daily Sync

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:  # 添加手动触发功能

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        path: my-repo  # 工作目录

    - name: Download files
      run: |
        mkdir -p my-repo/data
        curl -L https://raw.githubusercontent.com/v2ray/domain-list-community/558eeb914414ff1dc660282e91c6b173646e357a/data/steam -o my-repo/data/steam
        curl -L https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/SteamCN/SteamCN.list -o my-repo/data/SteamCN.list

    - name: Commit and push changes
      run: |
        cd my-repo
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add data/steam data/SteamCN.list
        git commit -m "Daily sync update" || echo "No changes to commit"
        git push origin main

